### ISSUE TITLE
What is the limit of this sheet ?

### ISSUE THREAD

**Issue by Meet-Miyani** [theapache64/retrosheet#29]
I would like to ask, that whether the sheet is capable of handling more than 100 request a time, because the google website mentions this.

**Reference : https://support.google.com/a/users/answer/9305987**
![image](https://user-images.githubusercontent.com/91192898/204251225-7f472c83-3186-4d46-b490-354ec8d73540.png)

**Reference : https://support.google.com/docs/answer/2494822?hl=en&visit_id=636973141922655348-330596984&rd=2**
![image](https://user-images.githubusercontent.com/91192898/204251446-37e4fbf1-3a08-4140-8295-6f8d669758fd.png)

**Comment by theapache64** [comment]
@Meet-Miyani I think those restrictions are only for the web interface. Did you get any limit error?

**Comment by Meet-Miyani** [comment]
Not yet, actually I wanted to make a production app with it, and for that reason I need to know the limits. Anyways its fine

**Comment by theapache64** [comment]
Cool
