### ISSUE TITLE
Support for accent marks

### ISSUE THREAD

**Issue by bernardog** [theapache64/retrosheet#31]
Letters with accent marks (á, ã, é, í, ó, ç, etc) are not making it to the Form, and, consequently, to the Sheet.
For example, "crédito" becomes "crdito".
Is it possible for retrosheet to support this, or is it a limitation of the Google Forms API?

**Comment by theapache64** [comment]
@bernardog I am really sorry I missed such an important issue ticket somehow . thanks for reporting this. The fix is on the way.

**Comment by mishael-w** [comment]
@theapache64  - Are you going to update the Android version to?

**Comment by theapache64** [comment]
@mishael-w Which version ur talking abt? If this is something other than accent marks, pls open a diff issue

**Comment by mishael-w** [comment]
@theapache64 - 
Sorry I wasn't clear.
I wanted to update to see if the new version will support Hebrew language (version 2.0.0-beta02 didn't support). 
I believe it falls under same category as accent marks, if not I'll gladly open new issue.

Tried the android sample app (The notes app), in the project there is 
usage of version 'retrosheet:2.0.0-beta02', when trying to update to version 2.0.2 - it fails.

**Comment by theapache64** [comment]
@mishael-w we don't have anything pointing to beta02 at this point. Also, 2.0.2 available in jitpack :  https://jitpack.io/#theapache64/retrosheet/2.0.2 

What was the error you were getting ? Are you sure you're on latest master?

**Comment by mishael-w** [comment]
I pulled the notes app repo, and it uses 2.0.0-beta02.
I get gradle build errors.
