### ISSUE TITLE
Enable to add adapter to Moshi

### ISSUE THREAD

**Issue by mateuy-dev** [theapache64/retrosheet#32]
The library uses an global Moshi instance that can't me modified.

`object MoshiUtils {
    val moshi: Moshi by lazy {
        Moshi.Builder()
            .build()
    }
}
`

A fast dirty solution would be just changeing it to var so that we could modify it and add adapters.

**Comment by theapache64** [comment]
Hey @mateuy-dev 

Sorry for the late reply. While I can make this change easily, I am curious about the use case. Why would you want to modify the Moshi instance? If it's a common use case, I can provide a better construct. Could you give me an example for this pls?

**Comment by theapache64** [comment]
I see two upvotes on the issue, and I think that's a good signal that someone else also aligns with your thoughts :)
I've added a `setMoshi` function to the retrosheet interceptor. You can override the Moshi behavior using this construct from `2.0.2`

**Comment by mateuy-dev** [comment]
Thanks.
If I remember it correctly, I needed to add a custom adapter.
